### ISSUE TITLE
get maps on activity or fragment

### ISSUE THREAD

**Issue by VictorHom** [AndroidHuddle/Huddle#12]
Get maps into a screen
check if it's possible to get onto fragment, otherwise stay on activity.

**Comment by aliciaphes** [comment]
@VictorHom @badhrijagan06 
Apparently the PlacePicker is full-screen by default and this cannot be configured.
I guess we're going to have to show it on the main activity and then return to the corresponding 'tabbed' fragment once the user picks a place, would you be ok with that?

**Comment by VictorHom** [comment]
ok sure. lets make that work. should it be the main activity though? it should be an event creation activity (doesn't exist yet) instead. 
@aliciaphes @badhrijagan06

**Comment by aliciaphes** [comment]
No no, obviously in the 'create event' activity, I meant 'main' meaning the activity where I was embedding the fragment  :)
@VictorHom @badhrijagan06

**Comment by VictorHom** [comment]
👍 +1

**Comment by aliciaphes** [comment]
Now after a place is selected in the place picker, we will display a mapfragment showing the place selected.
Might this be redundant...?

The place picker can also be re-launched.

Also let's keep in mind that maps might not work in all computers (see [this](https://guides.codepath.com/android/Collaborating-on-Projects-with-Git#creating-pull-requests) regarding debug.keystore for more details)
