### ISSUE TITLE
Implement geofencing for friends nearby

### ISSUE THREAD

**Issue by VictorHom** [AndroidHuddle/Huddle#13]
check what the capabilities and if it fits our use case.

**Comment by aliciaphes** [comment]
Looking into this.

**Comment by aliciaphes** [comment]
Still working on this :(
I am trying to get several examples I found online to work on either my phone or my emulator.
Also see #46

**Comment by aliciaphes** [comment]
This seems to work now. Will reopen if it's not the case.
