### ISSUE TITLE
choose a type of event to make

### ISSUE THREAD

**Issue by VictorHom** [AndroidHuddle/Huddle#20]
in the creation process, a user can pick what type of event, restaurant, custom event, movies, drinks, etc.

**Comment by aliciaphes** [comment]
This should go in CreateEventActivity.java (it only has a button for now)

**Comment by VictorHom** [comment]
cool. looking into this now

**Comment by VictorHom** [comment]
still in progress, but added a list with the listener in place. The next step is to pass the type of event and the user location so that we can create suggestions and pinpoint where the user should be on the map.

**Comment by aliciaphes** [comment]
Google Places automatically centers the map based on your (current user) current location the first time (at least for my tests so far).
The way I see it (but I might be wrong  :/ ), the whole point of Google Places is that it already identifies places around current location as suggestions (we can move around the world though, it updates with nearby places every time).
What Huddle does is after picking a place, it is then marked on our map fragment and that will be our 'venue' or 'location' for our event.

**Comment by VictorHom** [comment]
not using this page right now and removing from the page creation flow. Google Places API doesn't support a filter (marking only restaurants, bars, etc.)

The alternative, and as a next step, would be to support the filter. 

1. We can add the  list back into the page
2. Base on the type picked, we can query yelp for locations
3. take the lat-long and mark on a plain google maps without the places api use

will revisit later
