### ISSUE TITLE
request for user object given a particular sign up/ sign in

### ISSUE THREAD

**Issue by VictorHom** [AndroidHuddle/Huddle#32]

**Comment by aliciaphes** [comment]
Is here where we should retrieve the list of friends to have it available throughout the navigation flow?

**Comment by VictorHom** [comment]
sorry @aliciaphes I didn't see this until now. currently working on requesting for the user friends list. Currently, I plan on querying for a friends list when I am on the form creation page. Do you need it earlier?

**Comment by VictorHom** [comment]
otherwise, if you pull from master (merged in is #45 ) the user is requested from parse. Delete the app and restart it from the beginning. After you sign in, you can check the parse backend and your username, phone number, latitude, and longitude is stored.
